name: Build

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/dotnet/sdk:8.0
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Build
      run: dotnet build
    - name: Test
      run: dotnet test
    - name: Create NuGet packages
      run: |
        dotnet pack -c Release VASharp -o nuget/
    - name: Get version information
      uses: dotnet/nbgv@master
      id: nbgv
    - name: Publish NuGet packages as artifacts
      uses: actions/upload-artifact@v3
      with:
        name: VASharp-${{ steps.nbgv.outputs.SemVer2 }}
        path: nuget/
    - name: Publish NuGet packages to GitHub NuGet feed
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
      run: |
        dotnet nuget add source --username USERNAME --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"
        dotnet nuget push "nuget/*.nupkg" --api-key ${{ secrets.GITHUB_TOKEN }} --source "github"
    - name: Publish NuGet packages to NuGet.org feed
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
      run: |
        dotnet nuget push "nuget/*.nupkg" -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json
